# Options for networking
network:
  # The IP to host on (default: 127.0.0.1).
  # Use 0.0.0.0 to expose on all network adapters.
  host: 127.0.0.1

  # The port to host on (default: 5000).
  # Note: Recommended to use 5001 on MacOS because AirServer runs on port 5000
  port: 5000

  # Disable HTTP token authentication with requests.
  # WARNING: This will make your instance vulnerable!
  # Turn on this option if you are ONLY connecting from localhost.
  disable_auth: false

# Options for model overrides and loading
model:
  # Directory to look for models (default: models).
  # Windows users, do NOT put this path in quotes!
  model_dir:

  # An initial model to load.
  # Make sure the model is located in the model directory!
  # REQUIRED: This must be filled out to load a model on startup.
  model_name:

  # Max sequence length (default: Empty).
  # Fetched from the model's base sequence length in config.json by default.
  max_seq_len: 8192

  # Number of model layers to offload on the GPU (default: 0)
  num_gpu_layers: 0
